# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\user\atri\AssetBrowser\AssetBrowser\AssetBrowser\UI\AssetBrowser.ui'
#
# Created: Wed Aug 16 22:12:22 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_AssetBrowser(object):
    def setupUi(self, AssetBrowser):
        AssetBrowser.setObjectName("AssetBrowser")
        AssetBrowser.resize(1344, 728)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AssetBrowser.sizePolicy().hasHeightForWidth())
        AssetBrowser.setSizePolicy(sizePolicy)
        AssetBrowser.setMinimumSize(QtCore.QSize(1344, 728))
        AssetBrowser.setMaximumSize(QtCore.QSize(1344, 728))
        AssetBrowser.setStyleSheet("")
        self.centralWidget = QtGui.QWidget(AssetBrowser)
        self.centralWidget.setObjectName("centralWidget")
        self.assetWidget = QtGui.QWidget(self.centralWidget)
        self.assetWidget.setGeometry(QtCore.QRect(180, 10, 1151, 671))
        self.assetWidget.setObjectName("assetWidget")
        self.assetlistWidget = QtGui.QListWidget(self.assetWidget)
        self.assetlistWidget.setGeometry(QtCore.QRect(0, 0, 1151, 671))
        self.assetlistWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.assetlistWidget.setStyleSheet("")
        self.assetlistWidget.setFrameShape(QtGui.QFrame.StyledPanel)
        self.assetlistWidget.setLineWidth(1)
        self.assetlistWidget.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.assetlistWidget.setViewMode(QtGui.QListView.IconMode)
        self.assetlistWidget.setObjectName("assetlistWidget")
        self.categorylistWidget = QtGui.QListWidget(self.centralWidget)
        self.categorylistWidget.setGeometry(QtCore.QRect(10, 70, 161, 611))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.categorylistWidget.setFont(font)
        self.categorylistWidget.setStyleSheet("")
        self.categorylistWidget.setObjectName("categorylistWidget")
        self.widget = QtGui.QWidget(self.centralWidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 161, 51))
        self.widget.setStyleSheet("border: 1px  solid #343434;\n"
"\n"
"border-color: rgb(0, 0, 0);")
        self.widget.setObjectName("widget")
        self.categoryLabel = QtGui.QLabel(self.widget)
        self.categoryLabel.setGeometry(QtCore.QRect(7, 11, 83, 30))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.categoryLabel.sizePolicy().hasHeightForWidth())
        self.categoryLabel.setSizePolicy(sizePolicy)
        self.categoryLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.categoryLabel.setStyleSheet("font: 16pt \"Segoe UI\";\n"
"\n"
"border:0px solid #333;\n"
"")
        self.categoryLabel.setObjectName("categoryLabel")
        self.removeButton = QtGui.QPushButton(self.widget)
        self.removeButton.setGeometry(QtCore.QRect(130, 16, 25, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeButton.sizePolicy().hasHeightForWidth())
        self.removeButton.setSizePolicy(sizePolicy)
        self.removeButton.setMinimumSize(QtCore.QSize(25, 25))
        self.removeButton.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.removeButton.setFont(font)
        self.removeButton.setStyleSheet("border:0px")
        self.removeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeButton.setIcon(icon)
        self.removeButton.setIconSize(QtCore.QSize(16, 16))
        self.removeButton.setObjectName("removeButton")
        self.addButton = QtGui.QPushButton(self.widget)
        self.addButton.setGeometry(QtCore.QRect(100, 16, 25, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addButton.sizePolicy().hasHeightForWidth())
        self.addButton.setSizePolicy(sizePolicy)
        self.addButton.setMinimumSize(QtCore.QSize(25, 25))
        self.addButton.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.addButton.setFont(font)
        self.addButton.setStyleSheet("border:0px")
        self.addButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addButton.setIcon(icon1)
        self.addButton.setIconSize(QtCore.QSize(16, 16))
        self.addButton.setObjectName("addButton")
        AssetBrowser.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(AssetBrowser)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1344, 21))
        self.menuBar.setStyleSheet("")
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setStyleSheet("")
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        AssetBrowser.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(AssetBrowser)
        self.statusBar.setObjectName("statusBar")
        AssetBrowser.setStatusBar(self.statusBar)
        self.actionOpenDataBase = QtGui.QAction(AssetBrowser)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/openData.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenDataBase.setIcon(icon2)
        self.actionOpenDataBase.setObjectName("actionOpenDataBase")
        self.actionClose = QtGui.QAction(AssetBrowser)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon3)
        self.actionClose.setObjectName("actionClose")
        self.actionDocumentation = QtGui.QAction(AssetBrowser)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/doc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDocumentation.setIcon(icon4)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionAboutAuthor = QtGui.QAction(AssetBrowser)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAboutAuthor.setIcon(icon5)
        self.actionAboutAuthor.setObjectName("actionAboutAuthor")
        self.menuFile.addAction(self.actionOpenDataBase)
        self.menuFile.addAction(self.actionClose)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addAction(self.actionAboutAuthor)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(AssetBrowser)
        QtCore.QMetaObject.connectSlotsByName(AssetBrowser)

    def retranslateUi(self, AssetBrowser):
        AssetBrowser.setWindowTitle(QtGui.QApplication.translate("AssetBrowser", "AssetBrowser", None, QtGui.QApplication.UnicodeUTF8))
        self.categorylistWidget.setSortingEnabled(False)
        self.categoryLabel.setText(QtGui.QApplication.translate("AssetBrowser", "Catagory", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("AssetBrowser", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("AssetBrowser", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenDataBase.setText(QtGui.QApplication.translate("AssetBrowser", "OpenDataBase", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("AssetBrowser", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDocumentation.setText(QtGui.QApplication.translate("AssetBrowser", "Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAboutAuthor.setText(QtGui.QApplication.translate("AssetBrowser", "AboutAuthor", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
